import { demoUploadedDocumentUrl } from './applications.js'

/**
 * In-progress applications (not yet submitted), aligned with the student portal’s
 * draft/submission shape: partial `formValues` from the application form.
 */
export const applicationDrafts = [
  {
    id: 'DRAFT-2026-00041',
    userEmail: 'maria.garcia@email.com',
    applicantName: 'Maria Garcia',
    email: 'maria.garcia@email.com',
    phone: '+52 55 9102 4411',
    citizenship: 'Mexico',
    country: 'Mexico',
    program: 'MD Program',
    intake: 'September 2026',
    currentStepIndex: 2,
    currentStepTitle: 'Academic background',
    lastSavedAt: '2026-04-10T14:22:00.000Z',
    status: 'Draft',
    formValues: {
      title: 'Ms',
      firstName: 'Maria',
      surname: 'Garcia',
      email: 'maria.garcia@email.com',
      phoneMobile: '+52 55 9102 4411',
      citizenship: 'Mexico',
      programType: 'md',
      subProgram: 'md-standard',
      semester: 'September',
      year: '2026',
    },
  },
  {
    id: 'DRAFT-2026-00042',
    userEmail: 'james.okafor@email.com',
    applicantName: 'James Okafor',
    email: 'james.okafor@email.com',
    phone: '+233 24 555 0198',
    citizenship: 'Ghana',
    country: 'Ghana',
    program: 'Pre-Med',
    intake: 'January 2027',
    currentStepIndex: 4,
    currentStepTitle: 'Experience & motivation',
    lastSavedAt: '2026-04-12T09:05:00.000Z',
    status: 'Draft',
    formValues: {
      title: 'Mr',
      firstName: 'James',
      surname: 'Okafor',
      email: 'james.okafor@email.com',
      phoneMobile: '+233 24 555 0198',
      citizenship: 'Ghana',
      programType: 'pre-med',
      semester: 'January',
      year: '2027',
    },
  },
  {
    id: 'DRAFT-2026-00043',
    userEmail: 'yuki.tanaka@email.com',
    applicantName: 'Yuki Tanaka',
    email: 'yuki.tanaka@email.com',
    phone: '+81 90 1234 8899',
    citizenship: 'Japan',
    country: 'Japan',
    program: '',
    intake: '',
    currentStepIndex: 0,
    currentStepTitle: 'Personal details',
    lastSavedAt: '2026-04-14T16:40:00.000Z',
    status: 'Draft',
    formValues: {
      title: 'Mr',
      firstName: 'Yuki',
      surname: 'Tanaka',
      email: 'yuki.tanaka@email.com',
      phoneMobile: '+81 90 1234 8899',
      citizenship: 'Japan',
    },
  },
  {
    id: 'DRAFT-2026-00044',
    userEmail: 'sofia.martins@email.com',
    applicantName: 'Sofia Martins',
    email: 'sofia.martins@email.com',
    phone: '+55 11 98877 6655',
    citizenship: 'Brazil',
    country: 'Brazil',
    program: 'MD Program',
    intake: 'September 2026',
    currentStepIndex: 6,
    currentStepTitle: 'Documents',
    lastSavedAt: '2026-04-15T11:18:00.000Z',
    status: 'Draft',
    formValues: {
      title: 'Ms',
      firstName: 'Sofia',
      surname: 'Martins',
      email: 'sofia.martins@email.com',
      phoneMobile: '+55 11 98877 6655',
      citizenship: 'Brazil',
      programType: 'md',
      subProgram: 'md-accelerated',
      semester: 'September',
      year: '2026',
      englishProficiency: 'Native Speaker',
      passport: 'sofia-martins-passport.pdf',
      bankStatement: 'bank-statements-q1-2026.pdf',
      preMedTranscript: 'undergrad-transcript.pdf',
      _fileViewUrls: {
        passport: demoUploadedDocumentUrl,
        bankStatement: demoUploadedDocumentUrl,
        preMedTranscript: demoUploadedDocumentUrl,
      },
    },
  },
]

export function getDraftById(id) {
  return applicationDrafts.find((d) => d.id === id)
}
