/** Demo URL for “view uploaded document” in the admin Documents queue (opens in a new tab). */
export const demoUploadedDocumentUrl =
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'

export const applications = [
  {
    id: 'MUCM-2026-01402',
    name: 'Aisha Khan',
    citizenship: 'Pakistan',
    status: 'Validation',
    submittedAt: '2026-03-28',
    assignedOfficer: 'Dr. Ellis',
    daysInStage: 5,
    program: 'MD Program',
    intake: 'September 2026',
    country: 'Pakistan',
    phone: '+92 300 555 0192',
    email: 'aisha.khan@email.com',
    referredBy: 'Website',
    leadSource: 'Website',
    crmLinked: true,
    photoUrl: null,
    personal: {
      title: 'Ms',
      dob: '2002-04-12',
      passport: 'PK1234567',
      address: 'Lahore, Pakistan',
    },
    academic: {
      qualification: 'BSc Biology',
      institution: 'University of Punjab',
      personalStatement: 'Committed to rural healthcare and research…',
    },
    documents: [
      {
        id: 'd1',
        name: 'Passport (bio page)',
        status: 'verified',
        officer: 'Dr. Ellis',
        at: '2026-03-29',
        virusScan: 'clean',
        stale: false,
        uploadedAt: '2026-03-28',
        fileUrl: demoUploadedDocumentUrl,
        formField: 'passport',
      },
      {
        id: 'd2',
        name: 'Bank statement',
        status: 'pending',
        officer: null,
        at: null,
        virusScan: 'clean',
        stale: true,
        uploadedAt: '2026-01-10',
        fileUrl: demoUploadedDocumentUrl,
        formField: 'bankStatement',
      },
      {
        id: 'd3',
        name: 'Transcript',
        status: 'verified',
        officer: 'Dr. Ellis',
        at: '2026-03-29',
        virusScan: 'clean',
        stale: false,
        uploadedAt: '2026-03-27',
        fileUrl: demoUploadedDocumentUrl,
        formField: 'preMedTranscript',
      },
    ],
    financial: {
      payer: 'Sponsored by individual',
      sponsorName: 'R. Khan',
      payments: [
        {
          id: 'pay-aisha-1',
          type: 'Application Fee',
          amount: 'USD 150',
          currency: 'USD',
          status: 'Paid',
          ref: 'WIRE-9921',
          method: 'Wire transfer',
          recordedAt: '2026-03-29',
          instructionsSentAt: '2026-03-28',
        },
      ],
    },
    communications: [
      {
        id: 'c1',
        subject: 'Application received',
        at: '2026-03-28T10:02:00Z',
        status: 'delivered',
      },
      {
        id: 'c2',
        subject: 'Documents reminder',
        at: '2026-04-01T09:15:00Z',
        status: 'opened',
      },
    ],
    timeline: [
      { at: '2026-03-28T10:00:00Z', actor: 'System', action: 'Status → Submitted' },
      { at: '2026-03-29T14:20:00Z', actor: 'Dr. Ellis', action: 'Moved to Validation' },
    ],
    crm: {
      source: 'Organic search',
      channel: 'Web',
      agent: '—',
      interactions: 4,
      firstContact: '2026-02-10',
    },
  },
  {
    id: 'MUCM-2026-01388',
    name: 'James Osei',
    citizenship: 'Ghana',
    status: 'Application Fee',
    submittedAt: '2026-03-22',
    assignedOfficer: 'Ms. Porter',
    daysInStage: 3,
    program: 'MD Program',
    intake: 'September 2026',
    country: 'Ghana',
    phone: '+233 24 555 7711',
    email: 'j.osei@email.com',
    referredBy: 'Agent',
    leadSource: 'Agent',
    crmLinked: false,
    photoUrl: null,
    personal: { title: 'Mr', dob: '2001-11-02', passport: 'GH998877', address: 'Accra' },
    academic: {
      qualification: 'BSc Chemistry',
      institution: 'University of Ghana',
      personalStatement: '…',
    },
    documents: [],
    financial: {
      payer: 'Self-funded',
      sponsorName: null,
      payments: [
        {
          id: 'pay-james-1',
          type: 'Application Fee',
          amount: 'USD 150',
          currency: 'USD',
          status: 'Pending',
          ref: '—',
          method: 'Awaiting transfer',
          recordedAt: null,
          instructionsSentAt: '2026-03-23',
        },
      ],
    },
    communications: [],
    timeline: [],
    crm: null,
  },
  {
    id: 'MUCM-2026-01371',
    name: 'Maria Santos',
    citizenship: 'Brazil',
    status: 'Under Review',
    submittedAt: '2026-03-18',
    assignedOfficer: 'Dr. Ellis',
    daysInStage: 2,
    program: 'Pre-Med',
    intake: 'September 2026',
    country: 'Brazil',
    phone: '+55 11 98888 2211',
    email: 'maria.santos@email.com',
    referredBy: 'Referral MUCM-2026-00991',
    leadSource: 'Referral',
    crmLinked: true,
    photoUrl: null,
    personal: { title: 'Ms', dob: '2003-01-20', passport: 'BR445566', address: 'São Paulo' },
    academic: { qualification: 'High school + exams', institution: '—', personalStatement: '…' },
    documents: [],
    financial: {
      payer: 'Split',
      sponsorName: 'Parent',
      payments: [],
    },
    communications: [],
    timeline: [],
    crm: { source: 'Referral', channel: 'Alumni', agent: '—', interactions: 2, firstContact: '2026-01-05' },
  },
  {
    id: 'MUCM-2026-01204',
    name: 'Chen Wei',
    citizenship: 'China',
    status: 'Interview Scheduled',
    submittedAt: '2026-02-14',
    assignedOfficer: 'Dr. Ellis',
    daysInStage: 2,
    program: 'MD Program',
    intake: 'September 2026',
    country: 'China',
    phone: '+86 138 0000 1122',
    email: 'chen.wei@email.com',
    referredBy: 'Website',
    leadSource: 'Website',
    crmLinked: true,
    photoUrl: null,
    personal: { title: 'Mr', dob: '2000-08-30', passport: 'CN887766', address: 'Shanghai' },
    academic: { qualification: 'BSc Biochemistry', institution: 'Fudan University', personalStatement: '…' },
    documents: [
      {
        id: 'd-cw-1',
        name: 'Passport (bio page)',
        status: 'verified',
        officer: 'Dr. Ellis',
        at: '2026-02-18',
        virusScan: 'clean',
        stale: false,
        uploadedAt: '2026-02-16',
        fileUrl: demoUploadedDocumentUrl,
        formField: 'passport',
      },
    ],
    financial: {
      payer: 'Self-funded',
      sponsorName: null,
      payments: [
        {
          id: 'pay-cw-1',
          type: 'Application Fee',
          amount: 'USD 150',
          currency: 'USD',
          status: 'Paid',
          ref: 'WIRE-4401',
          method: 'Wire transfer',
          recordedAt: '2026-02-20',
          instructionsSentAt: '2026-02-15',
        },
      ],
    },
    communications: [],
    timeline: [],
    crm: { source: 'Website', channel: 'Web', agent: '—', interactions: 1, firstContact: '2026-02-01' },
    interview: {
      scheduledAt: '2026-04-18T18:00:00Z',
      timezone: 'AST (UTC−4)',
      mode: 'Video — Microsoft Teams',
      location: 'Link sent via interview invitation email',
      interviewers: ['Dr. A. Dean', 'Dr. M. Patel'],
      status: 'scheduled',
      inviteSentAt: '2026-04-08T09:15:00Z',
    },
  },
  {
    id: 'MUCM-2026-01190',
    name: 'Sofia Rossi',
    citizenship: 'Italy',
    status: 'Interview Complete',
    submittedAt: '2026-01-22',
    assignedOfficer: 'Ms. Porter',
    daysInStage: 4,
    program: 'MD Program',
    intake: 'September 2026',
    country: 'Italy',
    phone: '+39 320 555 8899',
    email: 'sofia.rossi@email.com',
    referredBy: 'Alumni Referral',
    leadSource: 'Referral',
    crmLinked: true,
    photoUrl: null,
    personal: { title: 'Ms', dob: '2001-12-05', passport: 'IT334455', address: 'Milan' },
    academic: { qualification: 'BSc Biology', institution: 'Università degli Studi', personalStatement: '…' },
    documents: [],
    financial: { payer: 'Self-funded', sponsorName: null, payments: [] },
    communications: [],
    timeline: [],
    crm: null,
    interview: {
      scheduledAt: '2026-03-25T15:30:00Z',
      timezone: 'AST (UTC−4)',
      mode: 'On campus — MUCM',
      location: 'Dean conference room',
      interviewers: ['Dr. A. Dean'],
      status: 'complete',
      inviteSentAt: '2026-03-10T08:00:00Z',
      evaluation: {
        submittedAt: '2026-03-26T11:20:00Z',
        submittedBy: 'Dr. A. Dean',
        recommendation: 'Recommend for admission',
        notes: 'Strong motivation and clear communication. Ready for committee review.',
        scores: { communication: 4, motivation: 5, academicFit: 4 },
      },
    },
  },
  {
    id: 'MUCM-2026-00977',
    name: 'David Okonkwo',
    citizenship: 'Nigeria',
    status: 'Enrolled',
    submittedAt: '2025-11-02',
    assignedOfficer: 'Dr. Ellis',
    daysInStage: 0,
    program: 'MD Program',
    intake: 'May 2026',
    country: 'Nigeria',
    phone: '+234 803 555 4411',
    email: 'd.okonkwo@email.com',
    referredBy: 'Education Agent',
    leadSource: 'Agent',
    crmLinked: true,
    photoUrl: null,
    personal: { title: 'Mr', dob: '1999-03-18', passport: 'NG112233', address: 'Lagos' },
    academic: { qualification: 'BSc Microbiology', institution: 'University of Lagos', personalStatement: '…' },
    documents: [],
    financial: {
      payer: 'Sponsored by individual',
      sponsorName: 'Parent',
      payments: [
        {
          id: 'pay-do-1',
          type: 'Application Fee',
          amount: 'USD 150',
          currency: 'USD',
          status: 'Paid',
          ref: 'WIRE-7788',
          method: 'Wire transfer',
          recordedAt: '2025-11-20',
          instructionsSentAt: '2025-11-12',
        },
        {
          id: 'pay-do-2',
          type: 'Registration Fee',
          amount: 'USD 2,500',
          currency: 'USD',
          status: 'Paid',
          ref: 'WIRE-7790',
          method: 'Wire transfer',
          recordedAt: '2026-01-08',
          instructionsSentAt: '2025-12-01',
        },
        {
          id: 'pay-do-3',
          type: 'Seat Reservation Fee',
          amount: 'USD 1,000',
          currency: 'USD',
          status: 'Paid',
          ref: 'WIRE-7794',
          method: 'Wire transfer',
          recordedAt: '2026-02-01',
          instructionsSentAt: '2026-01-15',
        },
      ],
    },
    communications: [],
    timeline: [],
    crm: null,
    enrollment: {
      studentId: 'MUCM-STU-2026-0044',
      enrolledAt: '2026-03-15',
      confirmedBy: 'Ms. Porter',
      notes: 'Welcome email sent; Phase 2 provisioning pending.',
    },
  },
  {
    id: 'MUCM-2026-01320',
    name: 'Elena Petrova',
    citizenship: 'Ukraine',
    status: 'Seat Reserved',
    submittedAt: '2026-03-05',
    assignedOfficer: 'Ms. Porter',
    daysInStage: 6,
    program: 'MD Program',
    intake: 'September 2026',
    country: 'Ukraine',
    phone: '+380 67 555 2211',
    email: 'e.petrova@email.com',
    referredBy: 'Search Engine',
    leadSource: 'Website',
    crmLinked: false,
    photoUrl: null,
    personal: { title: 'Ms', dob: '2002-02-28', passport: 'UA556677', address: 'Kyiv' },
    academic: { qualification: 'Pre-med coursework', institution: '—', personalStatement: '…' },
    documents: [
      {
        id: 'd-ep-1',
        name: 'Bank statement',
        status: 'pending',
        officer: null,
        at: null,
        virusScan: 'pending',
        stale: false,
        uploadedAt: '2026-04-14',
        fileUrl: demoUploadedDocumentUrl,
        formField: 'bankStatement',
      },
    ],
    financial: {
      payer: 'Self-funded',
      sponsorName: null,
      payments: [
        {
          id: 'pay-ep-1',
          type: 'Application Fee',
          amount: 'USD 150',
          currency: 'USD',
          status: 'Paid',
          ref: 'WIRE-6610',
          method: 'Wire transfer',
          recordedAt: '2026-03-08',
          instructionsSentAt: '2026-03-06',
        },
        {
          id: 'pay-ep-2',
          type: 'Registration Fee',
          amount: 'USD 2,500',
          currency: 'USD',
          status: 'Paid',
          ref: 'WIRE-6612',
          method: 'Wire transfer',
          recordedAt: '2026-03-28',
          instructionsSentAt: '2026-03-20',
        },
        {
          id: 'pay-ep-3',
          type: 'Seat Reservation Fee',
          amount: 'USD 1,000',
          currency: 'USD',
          status: 'Pending',
          ref: '—',
          method: 'Awaiting transfer',
          recordedAt: null,
          instructionsSentAt: '2026-04-10',
        },
      ],
    },
    communications: [],
    timeline: [],
    crm: null,
  },
]

export function getApplicationById(id) {
  return applications.find((a) => a.id === id) ?? null
}
